#Alfredo Moreira
#Put this file in a .circleci/ folder
#This file is to be used to run Github Status Checks
version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.1.3
jobs:
  build:
    docker:
      - image:  cimg/node:16.12.0
    working_directory: ~/control-panel
    steps:
      - checkout
      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-
      - run: 
          name: Check Node Version
          command: node --version
      - run:
          name: Install Packages
          command: yarn install
      #save cache for use next tests
      - save_cache:
         paths:
          - node_modules
         key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Compile Binary
          command: yarn build
  
  e2e:
    docker:
      - image: cypress/base:16.5.0
        environment:
          TERM: xterm
      ## MongoDB 
      - image: mongo:4.4.10
        environment:
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: asylum-connect
    working_directory: ~/control-panel
    steps:
      - checkout
      - run:
          name: Pull API code
          command: git clone --branch dev https://github.com/asylum-connect/catalog-api.git
      - run: 
          name: Create API Env File
          command: |
           cd catalog-api && cat \<< EOF > ./.env
           MAILGUN_API_KEY=$MAILGUN_API_KEY
           MAILGUN_DOMAIN=$MAILGUN_DOMAIN
           DB_URI=$DB_URI_STAGING
           ENV=TEST
           SHEETS_API_KEY=$SHEETS_API_KEY
           TEST_DB_URI=$TEST_DB_URI
           EOF
      - run:
          name: Install API Packages
          command: cd catalog-api && yarn install
      - run:
          name: "Seed Docker DB"
          command: cd catalog-api && export ROOT_DIR=catalog-api && yarn seed-docker-db
      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-
      - run: 
          name: Check Node Version
          command: node --version
      - run:
          name: Install Packages
          command: npm install
      - run:
          name: Install NYC
          command: npm i nyc
      - run:
          name: Install cypress
          command: npm i cypress
      #save cache for use next tests
      - save_cache:
         paths:
          - node_modules
          - "~./cache/Cypress"
         key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Pre E2E Commands"
          command: "yarn test:pre-e2e"
      - run:
          name: "E2E Automation"
          command: "yarn test:e2e:ci"
      - run:
          name: "Show Coverage"
          command: "yarn show-coverage"
      - codecov/upload:
          file: 'cypressCoverage/coverage-final.json'
          flags: 'Integration'
      - store_artifacts:
          path: ./cypressCoverage
          destination: E2E Coverage Reports
      - store_artifacts:
          path: "reports/"
          destination: E2E Test Reports 
    

workflows:
  version: 1
  pull_request:
    jobs: 
      - build
      - e2e